# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=200)),
                ('needle_name', models.CharField(max_length=200)),
                ('others', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IRE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.PositiveIntegerField()),
                ('time_duration', models.DurationField()),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liverdata.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Lesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesion_name', models.CharField(max_length=250)),
                ('lesion_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lesion_biopsy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MWA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.PositiveIntegerField()),
                ('time_duration', models.DurationField()),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liverdata.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=1)),
                ('study_site', models.CharField(default='Bern', max_length=100)),
                ('study_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RFA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.PositiveIntegerField()),
                ('time_duration', models.DurationField()),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liverdata.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(max_length=100)),
                ('lesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liverdata.Lesion')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatmentsession_date', models.DateTimeField(verbose_name='Treatment Session Date:')),
                ('treatment_nr', models.PositiveIntegerField()),
                ('treatment_type', models.CharField(choices=[('IR', 'Intervention'), ('LP', 'Laparoscopy'), ('Open', 'Surgery'), ('Resection', 'Resection'), ('Chemotherapy', 'Chemotherapy')], max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liverdata.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatmentsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liverdata.TreatmentSession'),
        ),
        migrations.AddField(
            model_name='rfa',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liverdata.Treatment'),
        ),
        migrations.AddField(
            model_name='mwa',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liverdata.Treatment'),
        ),
        migrations.AddField(
            model_name='lesion',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liverdata.Patient'),
        ),
        migrations.AddField(
            model_name='ire',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liverdata.Treatment'),
        ),
    ]
