# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesion_name', models.CharField(max_length=250)),
                ('lesion_size', models.IntegerField(default=0)),
                ('lesion_biopsy', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(max_length=10)),
                ('treatment_type', models.CharField(max_length=10)),
                ('treatment_date', models.DateTimeField(verbose_name='treatment date')),
                ('lesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liverdata.Lesion')),
            ],
        ),
        migrations.AddField(
            model_name='lesion',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liverdata.Patient'),
        ),
    ]
