# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liverdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesion',
            name='lesion_biopsy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_size',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_name',
            field=models.CharField(choices=[('RFA', 'Radio-frequency Ablation'), ('MWA', 'Microwave Ablation'), ('IRE', 'Irreversible electroporration'), ('R', 'Resection'), ('T', 'TACE'), ('C', 'Chemotherapy')], max_length=3),
        ),
    ]
