# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 08:22
from __future__ import unicode_literals

from django.db import migrations, models

def forwards_func(apps, schema_editor):
    TreatmentName = apps.get_model("liverdata", "TreatmentName")
    db_alias = schema_editor.connection.alias
    TreatmentName.objects.using(db_alias).bulk_create([
        TreatmentName(id=1, treatment_name="Radiofrequency Ablation", short_name="RFA"),
        TreatmentName(id=2, treatment_name="Microwave Ablation", short_name="MWA"),
        TreatmentName(id=3, treatment_name="Irreversible Electroporation", short_name="IRE"),
        TreatmentName(id=4, treatment_name="Resection", short_name="R"),
        TreatmentName(id=5, treatment_name="Transplantation", short_name="T"),
        TreatmentName(id=6, treatment_name="Transarterial Embolization", short_name="TAE"),
    ])


def reverse_func(apps, schema_editor):
    TreatmentName = apps.get_model("liverdata", "TreatmentName")
    db_alias = schema_editor.connection.alias
    TreatmentName.objects.using(db_alias).filter(id=1).delete()
    TreatmentName.objects.using(db_alias).filter(id=2).delete()
    TreatmentName.objects.using(db_alias).filter(id=3).delete()
    TreatmentName.objects.using(db_alias).filter(id=4).delete()
    TreatmentName.objects.using(db_alias).filter(id=5).delete()
    TreatmentName.objects.using(db_alias).filter(id=6).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('liverdata', '0002_auto_20171018_1021'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
