# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liverdata', '0003_initialize_treatmentname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentname',
            name='treatment_name',
            field=models.CharField(max_length=100),
        ),
    ]
