# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 08:43
from __future__ import unicode_literals

from django.db import migrations

def forwards_func(apps, schema_editor):
    LesionType = apps.get_model("liverdata", "LesionType")
    db_alias = schema_editor.connection.alias
    LesionType.objects.using(db_alias).bulk_create([
        LesionType(lesiontype_name="Unkown", lesiontype_shortname="---"),
        LesionType(lesiontype_name="Hepatocellular Carcinoma", lesiontype_shortname="HCC"),
        LesionType(lesiontype_name="Colorectal Livermetastasis", lesiontype_shortname="CRLM"),
    ])


def reverse_func(apps, schema_editor):
    TreatmentName = apps.get_model("liverdata", "LesionType")
    db_alias = schema_editor.connection.alias
    LesionType.objects.using(db_alias).filter(lesiontype_name="Unkown", lesiontype_shortname="---").delete()
    LesionType.objects.using(db_alias).filter(lesiontype_name="Hepatocellular Carcinoma", lesiontype_shortname="HCC").delete()
    LesionType.objects.using(db_alias).filter(lesiontype_name="Colorectal Livermetastasis", lesiontype_shortname="CRLM").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('liverdata', '0006_auto_20171018_1043'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
