# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liverdata', '0007_initialize_lesiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesion',
            name='lesiontype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='liverdata.LesionType'),
        ),
    ]
