# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liverdata', '0008_lesion_lesiontype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name_plural': 'Device'},
        ),
        migrations.AlterModelOptions(
            name='treatmentname',
            options={'verbose_name_plural': 'TreatmentName'},
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesion_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='study_name',
            field=models.CharField(blank=True, default='ClinicalStudyBern', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='study_site',
            field=models.CharField(blank=True, default='Bern', max_length=100),
        ),
    ]
