# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liverdata', '0009_auto_20171018_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesion',
            old_name='lesion_size',
            new_name='lesion_volume_ml',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='study_site',
            new_name='study_institution',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.AddField(
            model_name='patient',
            name='yearofbirth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
