# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liverdata', '0011_auto_20171019_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='Died'),
        ),
        migrations.AlterField(
            model_name='ire',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liverdata.Device'),
        ),
        migrations.AlterField(
            model_name='ire',
            name='treatment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liverdata.Treatment'),
        ),
        migrations.AlterField(
            model_name='lesion',
            name='lesiontype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='liverdata.LesionType'),
        ),
        migrations.AlterField(
            model_name='mwa',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liverdata.Device'),
        ),
        migrations.AlterField(
            model_name='mwa',
            name='treatment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liverdata.Treatment'),
        ),
        migrations.AlterField(
            model_name='rfa',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liverdata.Device'),
        ),
        migrations.AlterField(
            model_name='rfa',
            name='treatment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liverdata.Treatment'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatmentname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='liverdata.TreatmentName'),
        ),
        migrations.AlterField(
            model_name='treatmentsession',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='liverdata.Patient'),
        ),
    ]
