# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liverdata', '0012_auto_20171020_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trajectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrypoint_planned', models.CharField(max_length=500)),
                ('targetpoint_planned', models.CharField(max_length=500)),
                ('entrypoint_measured', models.CharField(max_length=500)),
                ('targetpoint_measured', models.CharField(max_length=500)),
                ('trajectory_nr', models.PositiveIntegerField(blank=True, null=True)),
                ('parent_trajectory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='liverdata.Trajectory')),
            ],
            options={
                'verbose_name_plural': 'Trajectory',
            },
        ),
        migrations.AddField(
            model_name='lesion',
            name='lesion_nr',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ire',
            name='trajectory_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liverdata.Trajectory'),
        ),
        migrations.AddField(
            model_name='mwa',
            name='trajectory_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liverdata.Trajectory'),
        ),
        migrations.AddField(
            model_name='rfa',
            name='trajectory_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liverdata.Trajectory'),
        ),
    ]
