# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liverdata', '0013_auto_20171020_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesion',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liverdata.Patient'),
        ),
    ]
