# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liverdata', '0015_auto_20171023_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tperrors',
            name='angularerror',
            field=models.FloatField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tperrors',
            name='lateralerror',
            field=models.FloatField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tperrors',
            name='longerror',
            field=models.FloatField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tperrors',
            name='residualerror',
            field=models.FloatField(max_length=500),
        ),
    ]
